package model.error;

public enum ERROR {
    ADD_CHILD_TO_SLIDE,
    BLANK_NAME,
    DELETE_WORKSPACE,
    NODE_NOT_SELECTED,
    PRESENTATION_NOT_SELECTED,
    PROJECT_NOT_SELECTED,
    WORKSPACE_NOT_SELECTED,
    WRONG_PATH,
}
