package model.message;

public enum NOTE {
    AUTHOR_CHANGED,
    THEME_CHANGED,
    NAME_CHANGED,
    CHILD_ADDED,
    CHILD_REMOVED,
    NODE_REMOVED,
    PRESENTATION_NAME_CHANGED,
    SLOT_ADDED,
    SLOT_DELETED,

}
